// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aikwyhepkmqxnxibvaae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpa3d5aGVwa21xeG54aWJ2YWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDI3NzksImV4cCI6MjA2Njc3ODc3OX0.cDS0eukhruOPh8EGu-pVIpRF_OoGXENb-8whLlsLROk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);